import React, { useState, useEffect } from 'react';
import { Navbar } from './components/Navbar';
import { LandingPage } from './components/LandingPage';
import { PromptGenerator } from './components/PromptGenerator';
import { LoadingScreen } from './components/LoadingScreen';
import { ResultPage } from './components/ResultPage';
import { IdeasPage } from './components/IdeasPage';
import { PricingPage } from './components/PricingPage';
import { PrivacyPage } from './components/PrivacyPage';
import { TermsPage } from './components/TermsPage';
import { ContactPage } from './components/ContactPage';
import { DirectorLogoIcon } from './components/DirectorLogo';
import { MasterPromptInput, MasterPromptResult, AiConceptCard } from './types';
import { generateLocalMasterPrompt } from './data/generatorEngine';

export default function App() {
  const [currentPath, setCurrentPath] = useState<string>(() => {
    if (typeof window !== 'undefined') {
      const p = window.location.pathname;
      if (p === '/generate' || p === '/result' || p === '/ideas' || p === '/pricing' || p === '/privacy' || p === '/terms' || p === '/contact') {
        return p;
      }
    }
    return '/';
  });

  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [showLoadingAnimation, setShowLoadingAnimation] = useState<boolean>(false);
  const [pendingResult, setPendingResult] = useState<MasterPromptResult | null>(null);
  const [activeResult, setActiveResult] = useState<MasterPromptResult | null>(null);
  const [initialGeneratorValues, setInitialGeneratorValues] = useState<Partial<MasterPromptInput>>({});

  // Sync route with browser popstate
  useEffect(() => {
    const handlePopState = () => {
      const path = window.location.pathname || '/';
      setCurrentPath(path);
    };
    window.addEventListener('popstate', handlePopState);
    return () => window.removeEventListener('popstate', handlePopState);
  }, []);

  const navigateTo = (path: string) => {
    window.history.pushState({}, '', path);
    setCurrentPath(path);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleGeneratePrompt = async (input: MasterPromptInput) => {
    setIsGenerating(true);
    setShowLoadingAnimation(true);

    try {
      const response = await fetch('/api/generate-master-prompt', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(input),
      });

      if (!response.ok) {
        throw new Error(`Server response error: ${response.status}`);
      }

      const data = await response.json();

      let resultObj: MasterPromptResult;
      if (data && data.masterPromptText) {
        const localFallback = generateLocalMasterPrompt(input);
        resultObj = {
          title: `${input.productName || 'Product'} — Master Prompt & Publishing Package`,
          subtitle: 'Generated by Director.ai • Complete Multi-Platform UGC Campaign Asset Pack',
          productName: input.productName || 'Featured Product',
          masterPromptText: data.masterPromptText,
          creativeStrategy: data.creativeStrategy || localFallback.creativeStrategy,
          youtubePackage: data.youtubePackage || localFallback.youtubePackage,
          instagramPackage: data.instagramPackage || localFallback.instagramPackage,
          facebookPackage: data.facebookPackage || localFallback.facebookPackage,
          generatedAt: new Date().toISOString(),
        };
      } else {
        resultObj = generateLocalMasterPrompt(input);
      }

      setPendingResult(resultObj);
    } catch (err) {
      console.warn('Backend API unavailable, using local high-performance engine:', err);
      const fallback = generateLocalMasterPrompt(input);
      setPendingResult(fallback);
    }
  };

  const handleLoadingComplete = () => {
    if (pendingResult) {
      setActiveResult(pendingResult);
      setPendingResult(null);
    }
    setIsGenerating(false);
    setShowLoadingAnimation(false);
    navigateTo('/result');
  };

  const handleCreateAnother = () => {
    setActiveResult(null);
    setPendingResult(null);
    setInitialGeneratorValues({});
    navigateTo('/generate');
  };

  const handleSelectConcept = (concept: AiConceptCard) => {
    setInitialGeneratorValues({
      productName: concept.productNameExample,
      targetAudience: concept.targetAudience,
    });
    navigateTo('/generate');
  };

  return (
    <div className="min-h-screen bg-[#09090B] text-[#FAFAFA] flex flex-col font-sans selection:bg-[#8B5CF6]/30">
      <Navbar currentPath={currentPath} onNavigate={navigateTo} />

      <main className="flex-1">
        {showLoadingAnimation ? (
          <LoadingScreen onComplete={handleLoadingComplete} />
        ) : (
          <>
            {currentPath === '/' && (
              <LandingPage onNavigate={navigateTo} />
            )}

            {currentPath === '/generate' && (
              <PromptGenerator
                onGenerate={handleGeneratePrompt}
                isGenerating={isGenerating}
                initialValues={initialGeneratorValues}
                onNavigate={navigateTo}
              />
            )}

            {currentPath === '/result' && activeResult && (
              <ResultPage
                result={activeResult}
                onCreateAnother={handleCreateAnother}
              />
            )}

            {/* Fallback for result page if refreshed or accessed directly without memory state */}
            {currentPath === '/result' && !activeResult && (
              <div className="min-h-[calc(100vh-4rem)] flex flex-col items-center justify-center p-6 text-center">
                <div className="bg-[#111113] border border-[#27272A] p-8 rounded-3xl max-w-md shadow-2xl">
                  <h2 className="text-xl font-bold text-[#FAFAFA] mb-2">No Active Prompt in Memory</h2>
                  <p className="text-xs text-[#A1A1AA] mb-6 leading-relaxed font-mono">
                    "Your ideas stay yours." Prompts are held strictly in temporary RAM and erased upon page refresh.
                  </p>
                  <button
                    onClick={() => navigateTo('/generate')}
                    className="px-6 py-3 bg-[#8B5CF6] hover:bg-[#A78BFA] text-white text-xs font-semibold rounded-xl cursor-pointer transition-colors shadow-lg shadow-[#8B5CF6]/20"
                  >
                    Generate Master Prompt
                  </button>
                </div>
              </div>
            )}

            {currentPath === '/ideas' && (
              <IdeasPage onSelectConcept={handleSelectConcept} />
            )}

            {currentPath === '/pricing' && (
              <PricingPage onNavigate={navigateTo} />
            )}

            {currentPath === '/privacy' && <PrivacyPage />}

            {currentPath === '/terms' && <TermsPage />}

            {currentPath === '/contact' && <ContactPage />}
          </>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-[#27272A] py-8 px-4 text-center text-xs text-[#A1A1AA]">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 font-mono">
            <DirectorLogoIcon className="h-6 w-auto" />
            <span className="font-bold text-[#FAFAFA]">Director.ai</span>
            <span>— AI UGC Advertisement Master Prompt Generator</span>
          </div>

          <div className="flex items-center gap-4 text-xs font-medium">
            <button onClick={() => navigateTo('/ideas')} className="hover:text-white cursor-pointer transition-colors">
              Trending Concepts
            </button>
            <button onClick={() => navigateTo('/pricing')} className="hover:text-white cursor-pointer transition-colors">
              Pricing
            </button>
            <button onClick={() => navigateTo('/privacy')} className="hover:text-white cursor-pointer transition-colors">
              Privacy
            </button>
            <button onClick={() => navigateTo('/terms')} className="hover:text-white cursor-pointer transition-colors">
              Terms
            </button>
            <button onClick={() => navigateTo('/contact')} className="hover:text-white cursor-pointer transition-colors">
              Contact
            </button>
          </div>
        </div>
      </footer>
    </div>
  );
}
